services:
  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    ports:
      - "5432:5432"
    volumes:
     - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: psql -U postgres -tAc 'select 1' -d postgres
      interval: 15s
      timeout: 10s
      retries: 10

volumes:
  postgres_data:
